## Regression

In [47]:
import numpy as np

np.random.seed(4)
height=np.random.randint(10,50,30)
age=np.random.randint(18,40,30)

In [48]:
age

array([34, 35, 27, 34, 30, 36, 21, 29, 36, 24, 25, 31, 28, 25, 27, 36, 39,
       37, 34, 39, 33, 22, 29, 37, 26, 23, 26, 25, 18, 22])

In [49]:
height

array([15, 11, 33, 18, 19, 49, 40, 46, 48, 13, 10, 31, 31, 19, 48, 48, 12,
       40, 18, 12, 33, 42, 43, 42, 38, 13, 25, 44, 41, 27])

In [50]:
from sklearn.linear_model import LinearRegression

In [53]:
linear_reg=LinearRegression()

In [ ]:
#height which is dependent variable should be one dimentional array i/e need no reshape like age

In [55]:
age=age.reshape(-1,1)

In [56]:
age

array([[34],
       [35],
       [27],
       [34],
       [30],
       [36],
       [21],
       [29],
       [36],
       [24],
       [25],
       [31],
       [28],
       [25],
       [27],
       [36],
       [39],
       [37],
       [34],
       [39],
       [33],
       [22],
       [29],
       [37],
       [26],
       [23],
       [26],
       [25],
       [18],
       [22]])

In [57]:
linear_reg.fit(age,height)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [58]:
linear_reg.intercept_

35.29747832939322

In [59]:
linear_reg.coef_

array([-0.16883373])

In [63]:
linear_reg.predict([[20]])

array([31.92080378])